services:
  web1:
    restart: always
    build: ./app
    command: bash -c "
            python manage.py migrate
            && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - djsrc:/usr/src/app
    # ports:
    #   - 8000:8000
    depends_on:
      - pgdb

  web2:
    restart: always
    build: ./app
    command: bash -c "
            python manage.py migrate
            && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - djsrc:/usr/src/app
    depends_on:
      - pgdb

  web3:
    restart: always
    build: ./app
    command: bash -c "
            python manage.py migrate
            && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - djsrc:/usr/src/app
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    env_file:
      - ./app/cryptoclicker/.env
    
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web1
      - web2
      - web3

volumes:
  pgdbdata: null
  djsrc: 