# Generated by Django 5.0.6 on 2024-05-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0002_alter_cryptoclicker_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CryptoClicker',
            new_name='Clicker',
        ),
    ]
