# Generated by Django 5.0.6 on 2024-05-10 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0003_rename_cryptoclicker_clicker'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clicker',
            table=None,
        ),
    ]
