# Generated by Django 5.0.6 on 2024-05-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cryptoclicker',
            table='Crypto_clicker',
        ),
    ]
